name: test_mac
on: push
jobs: 
  build:
    runs-on: macos-12
    steps: 
      - name: download llamafile
        run: curl -L -o llamafile-0.6.zip https://github.com/Mozilla-Ocho/llamafile/releases/download/0.6/llamafile-0.6.zip
      - name: unzip llamafile
        run: unzip llamafile-0.6.zip
      - name: ls
        run: ls -R llamafile*
      - name: chmod
        run: chmod -R a+rwx llamafile*
      - name: download model
        run: curl -L -o model.gguf https://huggingface.co/afrideva/tiny-random-BloomForCausalLM-GGUF/resolve/main/tiny-random-bloomforcausallm.q2_k.gguf?download=true
      - name: run command
        run: llamafile-0.6/bin/llamafile --port 13333 -m model.gguf --log-disable --nobrowser
        timeout-minutes: 2