name: test_mac
on: push
jobs: 
  build:
    runs-on: macos-12
    steps: 
      - name: download llamafile
        run: curl -o llamafile-0.6.zip https://github.com/Mozilla-Ocho/llamafile/releases/download/0.6/llamafile-0.6.zip
      - name: unzip llamafile
        run: unzip llamafile-0.6.zip
      - name: ls
        run: ls -R llamafile*
      - name: chmod
        run: chmod -R a+rwx llamafile*
      - name: download model
        run: curl -o model.gguf https://huggingface.co/TheBloke/TinyLlama-1.1B-Chat-v1.0-GGUF/resolve/main/tinyllama-1.1b-chat-v1.0.Q2_K.gguf?download=true
      - name: run command
        run: llamafile-0.6/bin/llamafile  --port 13333 -m model.gguf --log-disable --nobrowser